server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # --- Job 1: Logs de Sistema (Auth/SSH) ---
  # Detecta intentos de login (Fuerza bruta)
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        host: vps-ovh-monitoring
        __path__: /var/log/auth.log

  # --- Job 2: Logs Generales (Syslog/Kern) ---
  # Errores generales del kernel o aplicaciones
  - job_name: syslog
    static_configs:
    - targets:
        - localhost
      labels:
        job: syslog
        host: vps-ovh-monitoring
        __path__: /var/log/syslog

  # --- Job 3: Logs de Docker ---
  # Para ver qué les pasa a los contenedores de monitoreo
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'

# ... (otros jobs anteriores)

  # --- AÑADIR ESTO AL FINAL ---
  - job_name: wordpress_security
    static_configs:
      - targets:
          - localhost
        labels:
          job: wordpress_security
          host: vps-ovh
          __path__: /var/log/wordpress_audit/auth_audit.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            event: event
            user_id: user_id
            remote_ip: remote_ip
            status: status
      - labels:
          level:
          event:
          status:
      - timestamp:
          source: timestamp
          format: RFC3339
